site_name: Uvent Documentation
site_description: High-performance asynchronous I/O library for modern C++23
site_url: https://usub-development.github.io/uvent/
repo_url: https://github.com/Usub-development/uvent
repo_name: Usub-development/uvent
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search
  - autorefs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - attr_list
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Quick Start: quick-start.md
  - Core Runtime:
      - Uvent: uvent.md
      - System Primitives: system_primitives.md
  - Coroutines:
      - Awaitable: awaitable.md
      - Awaitable Frame: awaitable_frame.md
  - Networking:
      - Socket: socket.md
  - Delayed tasks:
      - Timers: timers.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Usub-development/uvent
      name: GitHub Repository
    - icon: fontawesome/solid/star
      link: https://github.com/Usub-development/uvent/stargazers
      name: Star on GitHub

copyright: >
  Copyright &copy; 2025 Usub-development, Kirill Zhukov (g2px1)